SHELL := /bin/bash
.DEFAULT_GOAL := help

ROOT_DIR := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))

# Tracked defaults plus ignored machine-local overrides. Command-line
# assignments still take precedence:
#   make build-cuda WHISPER_CUDA_BUILD_JOBS=4
-include $(ROOT_DIR)/.env
-include $(ROOT_DIR)/.env.local

WHISPER_CPP_REPO ?= https://github.com/ggml-org/whisper.cpp.git
WHISPER_CPP_REF ?= v1.9.1
SOURCE_DIR ?= .cache/whisper.cpp
BUILD_DIR ?= .build/native
OUTPUT_DIR ?= output
MODEL_DIR ?= output/models
BUILD_PROFILE ?= native
ARCHIVE_PATH ?=
CMAKE_GENERATOR ?= auto
BUILD_JOBS ?= auto
CMAKE_C_COMPILER ?=
CMAKE_CXX_COMPILER ?=
CMAKE_CUDA_COMPILER ?=
CMAKE_CUDA_HOST_COMPILER ?=
CMAKE_C_COMPILER_LAUNCHER ?=
CMAKE_CXX_COMPILER_LAUNCHER ?=
CMAKE_CUDA_COMPILER_LAUNCHER ?=
CMAKE_C_FLAGS ?=
CMAKE_CXX_FLAGS ?=
CMAKE_CUDA_FLAGS ?=
SCCACHE_DIR ?=
SCCACHE_SERVER_UDS ?=
BUILD_CLI ?= 1
BUILD_SERVER ?= 1
GGML_NATIVE ?= 1
ENABLE_LTO ?= 1
ENABLE_CCACHE ?= 1
ENABLE_OPENMP ?= 1
ENABLE_CPU_REPACK ?= 1
ENABLE_FAST_MATH ?= 0
ENABLE_BLAS ?= 0
BLAS_VENDOR ?= OpenBLAS
ENABLE_CUDA ?= 0
CUDA_ARCHS ?= auto
ENABLE_CUDA_FA ?= 1
ENABLE_CUDA_FA_ALL_QUANTS ?= 0
CUDA_FORCE_MMQ ?= 0
CUDA_FORCE_CUBLAS ?= 0
CUDA_NO_PEER_COPY ?= 0
CUDA_NO_VMM ?= 0
ENABLE_CUDA_GRAPHS ?= 0
ENABLE_CUDA_NCCL ?= 0
CUDA_COMPRESSION_MODE ?= size
ENABLE_CUDA_GLIBC_COMPAT ?= 0
CUDA_GLIBC_HEADER ?=
CUDA_GLIBC_COMPAT_DIR ?=
ENABLE_HIP ?= 0
AMDGPU_TARGETS ?= auto
ENABLE_VULKAN ?= 0
ENABLE_SYCL ?= 0
ENABLE_SYCL_F16 ?= 0
SYCL_TARGET ?= INTEL
SYCL_DEVICE_ARCH ?=
ENABLE_OPENVINO ?= 0
ENABLE_FFMPEG ?= 0
STRIP_BINARY ?= 1
OFFLINE ?= 0
SOURCE_UPDATE ?= 0
FORCE_SOURCE_RESET ?= 0
HF_TOKEN ?=
STRICT_RESOURCES ?= 0
FORCE_DOWNLOAD ?= 0
ALLOW_EXTERNAL_DIRS ?= 0
RUNTIME_THREADS ?= auto
EXTRA_CMAKE_ARGS ?=
EXTRA_C_FLAGS ?=
EXTRA_CXX_FLAGS ?=
EXTRA_CUDA_FLAGS ?=

# Profile fallbacks remain repository-local if the tracked .env is removed.
# The checked-in .env replaces these with the requested /pool paths.
WHISPER_RAM_SOURCE_DIR ?= .cache/whisper.cpp
WHISPER_RAM_BUILD_DIR ?= .build/ram
WHISPER_RAM_OUTPUT_DIR ?= output/ram
WHISPER_RAM_MODEL_DIR ?= output/models
WHISPER_RAM_ARCHIVE_PATH ?= output/whisper-ram.tar.gz
WHISPER_RAM_SCCACHE_DIR ?= .cache/sccache/ram
WHISPER_RAM_SCCACHE_SERVER_UDS ?= .cache/sccache/ram/server.sock
WHISPER_RAM_CMAKE_GENERATOR ?= auto
WHISPER_RAM_BUILD_JOBS ?= auto
WHISPER_RAM_CMAKE_C_COMPILER ?=
WHISPER_RAM_CMAKE_CXX_COMPILER ?=
WHISPER_RAM_CMAKE_CUDA_COMPILER ?=
WHISPER_RAM_CMAKE_CUDA_HOST_COMPILER ?=
WHISPER_RAM_CMAKE_C_COMPILER_LAUNCHER ?=
WHISPER_RAM_CMAKE_CXX_COMPILER_LAUNCHER ?=
WHISPER_RAM_CMAKE_CUDA_COMPILER_LAUNCHER ?=
WHISPER_RAM_CMAKE_C_FLAGS ?=
WHISPER_RAM_CMAKE_CXX_FLAGS ?=
WHISPER_RAM_CMAKE_CUDA_FLAGS ?=
WHISPER_RAM_BUILD_CLI ?= 1
WHISPER_RAM_BUILD_SERVER ?= 1
WHISPER_RAM_GGML_NATIVE ?= 1
WHISPER_RAM_ENABLE_LTO ?= 1
WHISPER_RAM_ENABLE_CCACHE ?= 0
WHISPER_RAM_ENABLE_OPENMP ?= 1
WHISPER_RAM_ENABLE_CPU_REPACK ?= 1
WHISPER_RAM_ENABLE_FAST_MATH ?= 0
WHISPER_RAM_ENABLE_BLAS ?= 0
WHISPER_RAM_BLAS_VENDOR ?= OpenBLAS
WHISPER_RAM_ENABLE_CUDA ?= 0
WHISPER_RAM_CUDA_ARCHS ?= auto
WHISPER_RAM_ENABLE_CUDA_FA ?= 0
WHISPER_RAM_ENABLE_CUDA_FA_ALL_QUANTS ?= 0
WHISPER_RAM_CUDA_FORCE_MMQ ?= 0
WHISPER_RAM_CUDA_FORCE_CUBLAS ?= 0
WHISPER_RAM_CUDA_NO_PEER_COPY ?= 0
WHISPER_RAM_CUDA_NO_VMM ?= 0
WHISPER_RAM_ENABLE_CUDA_GRAPHS ?= 0
WHISPER_RAM_ENABLE_CUDA_NCCL ?= 0
WHISPER_RAM_CUDA_COMPRESSION_MODE ?= size
WHISPER_RAM_ENABLE_CUDA_GLIBC_COMPAT ?= 0
WHISPER_RAM_CUDA_GLIBC_HEADER ?=
WHISPER_RAM_CUDA_GLIBC_COMPAT_DIR ?=
WHISPER_RAM_ENABLE_HIP ?= 0
WHISPER_RAM_AMDGPU_TARGETS ?= auto
WHISPER_RAM_ENABLE_VULKAN ?= 0
WHISPER_RAM_ENABLE_SYCL ?= 0
WHISPER_RAM_ENABLE_SYCL_F16 ?= 0
WHISPER_RAM_SYCL_TARGET ?= INTEL
WHISPER_RAM_SYCL_DEVICE_ARCH ?=
WHISPER_RAM_ENABLE_OPENVINO ?= 0
WHISPER_RAM_ENABLE_FFMPEG ?= 0
WHISPER_RAM_STRIP_BINARY ?= 1
WHISPER_RAM_EXTRA_CMAKE_ARGS ?=
WHISPER_RAM_EXTRA_C_FLAGS ?=
WHISPER_RAM_EXTRA_CXX_FLAGS ?=
WHISPER_RAM_EXTRA_CUDA_FLAGS ?=

WHISPER_CUDA_SOURCE_DIR ?= .cache/whisper.cpp
WHISPER_CUDA_BUILD_DIR ?= .build/cuda
WHISPER_CUDA_OUTPUT_DIR ?= output/cuda
WHISPER_CUDA_MODEL_DIR ?= output/models
WHISPER_CUDA_ARCHIVE_PATH ?= output/whisper-cuda.tar.gz
WHISPER_CUDA_SCCACHE_DIR ?= .cache/sccache/cuda
WHISPER_CUDA_SCCACHE_SERVER_UDS ?= .cache/sccache/cuda/server.sock
WHISPER_CUDA_CMAKE_GENERATOR ?= auto
WHISPER_CUDA_BUILD_JOBS ?= auto
WHISPER_CUDA_CMAKE_C_COMPILER ?=
WHISPER_CUDA_CMAKE_CXX_COMPILER ?=
WHISPER_CUDA_CMAKE_CUDA_COMPILER ?= nvcc
WHISPER_CUDA_CMAKE_CUDA_HOST_COMPILER ?=
WHISPER_CUDA_CMAKE_C_COMPILER_LAUNCHER ?=
WHISPER_CUDA_CMAKE_CXX_COMPILER_LAUNCHER ?=
WHISPER_CUDA_CMAKE_CUDA_COMPILER_LAUNCHER ?=
WHISPER_CUDA_CMAKE_C_FLAGS ?=
WHISPER_CUDA_CMAKE_CXX_FLAGS ?=
WHISPER_CUDA_CMAKE_CUDA_FLAGS ?=
WHISPER_CUDA_BUILD_CLI ?= 1
WHISPER_CUDA_BUILD_SERVER ?= 1
WHISPER_CUDA_GGML_NATIVE ?= 1
WHISPER_CUDA_ENABLE_LTO ?= 1
WHISPER_CUDA_ENABLE_CCACHE ?= 0
WHISPER_CUDA_ENABLE_OPENMP ?= 1
WHISPER_CUDA_ENABLE_CPU_REPACK ?= 1
WHISPER_CUDA_ENABLE_FAST_MATH ?= 0
WHISPER_CUDA_ENABLE_BLAS ?= 0
WHISPER_CUDA_BLAS_VENDOR ?= OpenBLAS
WHISPER_CUDA_ENABLE_CUDA ?= 1
WHISPER_CUDA_CUDA_ARCHS ?= 61
WHISPER_CUDA_ENABLE_CUDA_FA ?= 1
WHISPER_CUDA_ENABLE_CUDA_FA_ALL_QUANTS ?= 0
WHISPER_CUDA_CUDA_FORCE_MMQ ?= 0
WHISPER_CUDA_CUDA_FORCE_CUBLAS ?= 0
WHISPER_CUDA_CUDA_NO_PEER_COPY ?= 1
WHISPER_CUDA_CUDA_NO_VMM ?= 0
WHISPER_CUDA_ENABLE_CUDA_GRAPHS ?= 0
WHISPER_CUDA_ENABLE_CUDA_NCCL ?= 0
WHISPER_CUDA_CUDA_COMPRESSION_MODE ?= size
WHISPER_CUDA_ENABLE_CUDA_GLIBC_COMPAT ?= 0
WHISPER_CUDA_CUDA_GLIBC_HEADER ?=
WHISPER_CUDA_CUDA_GLIBC_COMPAT_DIR ?=
WHISPER_CUDA_ENABLE_HIP ?= 0
WHISPER_CUDA_AMDGPU_TARGETS ?= auto
WHISPER_CUDA_ENABLE_VULKAN ?= 0
WHISPER_CUDA_ENABLE_SYCL ?= 0
WHISPER_CUDA_ENABLE_SYCL_F16 ?= 0
WHISPER_CUDA_SYCL_TARGET ?= INTEL
WHISPER_CUDA_SYCL_DEVICE_ARCH ?=
WHISPER_CUDA_ENABLE_OPENVINO ?= 0
WHISPER_CUDA_ENABLE_FFMPEG ?= 0
WHISPER_CUDA_STRIP_BINARY ?= 1
WHISPER_CUDA_EXTRA_CMAKE_ARGS ?=
WHISPER_CUDA_EXTRA_C_FLAGS ?=
WHISPER_CUDA_EXTRA_CXX_FLAGS ?=
WHISPER_CUDA_EXTRA_CUDA_FLAGS ?=

RAM_PROFILE_TARGETS := build-ram doctor-ram info-ram verify-ram clean-ram
CUDA_PROFILE_TARGETS := build-cuda doctor-cuda info-cuda verify-cuda clean-cuda

$(RAM_PROFILE_TARGETS): BUILD_PROFILE := ram
$(RAM_PROFILE_TARGETS): SOURCE_DIR := $(WHISPER_RAM_SOURCE_DIR)
$(RAM_PROFILE_TARGETS): BUILD_DIR := $(WHISPER_RAM_BUILD_DIR)
$(RAM_PROFILE_TARGETS): OUTPUT_DIR := $(WHISPER_RAM_OUTPUT_DIR)
$(RAM_PROFILE_TARGETS): MODEL_DIR := $(WHISPER_RAM_MODEL_DIR)
$(RAM_PROFILE_TARGETS): ARCHIVE_PATH := $(WHISPER_RAM_ARCHIVE_PATH)
$(RAM_PROFILE_TARGETS): SCCACHE_DIR := $(WHISPER_RAM_SCCACHE_DIR)
$(RAM_PROFILE_TARGETS): SCCACHE_SERVER_UDS := $(WHISPER_RAM_SCCACHE_SERVER_UDS)
$(RAM_PROFILE_TARGETS): CMAKE_GENERATOR := $(WHISPER_RAM_CMAKE_GENERATOR)
$(RAM_PROFILE_TARGETS): BUILD_JOBS := $(WHISPER_RAM_BUILD_JOBS)
$(RAM_PROFILE_TARGETS): CMAKE_C_COMPILER := $(WHISPER_RAM_CMAKE_C_COMPILER)
$(RAM_PROFILE_TARGETS): CMAKE_CXX_COMPILER := $(WHISPER_RAM_CMAKE_CXX_COMPILER)
$(RAM_PROFILE_TARGETS): CMAKE_CUDA_COMPILER := $(WHISPER_RAM_CMAKE_CUDA_COMPILER)
$(RAM_PROFILE_TARGETS): CMAKE_CUDA_HOST_COMPILER := $(WHISPER_RAM_CMAKE_CUDA_HOST_COMPILER)
$(RAM_PROFILE_TARGETS): CMAKE_C_COMPILER_LAUNCHER := $(WHISPER_RAM_CMAKE_C_COMPILER_LAUNCHER)
$(RAM_PROFILE_TARGETS): CMAKE_CXX_COMPILER_LAUNCHER := $(WHISPER_RAM_CMAKE_CXX_COMPILER_LAUNCHER)
$(RAM_PROFILE_TARGETS): CMAKE_CUDA_COMPILER_LAUNCHER := $(WHISPER_RAM_CMAKE_CUDA_COMPILER_LAUNCHER)
$(RAM_PROFILE_TARGETS): CMAKE_C_FLAGS := $(WHISPER_RAM_CMAKE_C_FLAGS)
$(RAM_PROFILE_TARGETS): CMAKE_CXX_FLAGS := $(WHISPER_RAM_CMAKE_CXX_FLAGS)
$(RAM_PROFILE_TARGETS): CMAKE_CUDA_FLAGS := $(WHISPER_RAM_CMAKE_CUDA_FLAGS)
$(RAM_PROFILE_TARGETS): BUILD_CLI := $(WHISPER_RAM_BUILD_CLI)
$(RAM_PROFILE_TARGETS): BUILD_SERVER := $(WHISPER_RAM_BUILD_SERVER)
$(RAM_PROFILE_TARGETS): GGML_NATIVE := $(WHISPER_RAM_GGML_NATIVE)
$(RAM_PROFILE_TARGETS): ENABLE_LTO := $(WHISPER_RAM_ENABLE_LTO)
$(RAM_PROFILE_TARGETS): ENABLE_CCACHE := $(WHISPER_RAM_ENABLE_CCACHE)
$(RAM_PROFILE_TARGETS): ENABLE_OPENMP := $(WHISPER_RAM_ENABLE_OPENMP)
$(RAM_PROFILE_TARGETS): ENABLE_CPU_REPACK := $(WHISPER_RAM_ENABLE_CPU_REPACK)
$(RAM_PROFILE_TARGETS): ENABLE_FAST_MATH := $(WHISPER_RAM_ENABLE_FAST_MATH)
$(RAM_PROFILE_TARGETS): ENABLE_BLAS := $(WHISPER_RAM_ENABLE_BLAS)
$(RAM_PROFILE_TARGETS): BLAS_VENDOR := $(WHISPER_RAM_BLAS_VENDOR)
$(RAM_PROFILE_TARGETS): ENABLE_CUDA := $(WHISPER_RAM_ENABLE_CUDA)
$(RAM_PROFILE_TARGETS): CUDA_ARCHS := $(WHISPER_RAM_CUDA_ARCHS)
$(RAM_PROFILE_TARGETS): ENABLE_CUDA_FA := $(WHISPER_RAM_ENABLE_CUDA_FA)
$(RAM_PROFILE_TARGETS): ENABLE_CUDA_FA_ALL_QUANTS := $(WHISPER_RAM_ENABLE_CUDA_FA_ALL_QUANTS)
$(RAM_PROFILE_TARGETS): CUDA_FORCE_MMQ := $(WHISPER_RAM_CUDA_FORCE_MMQ)
$(RAM_PROFILE_TARGETS): CUDA_FORCE_CUBLAS := $(WHISPER_RAM_CUDA_FORCE_CUBLAS)
$(RAM_PROFILE_TARGETS): CUDA_NO_PEER_COPY := $(WHISPER_RAM_CUDA_NO_PEER_COPY)
$(RAM_PROFILE_TARGETS): CUDA_NO_VMM := $(WHISPER_RAM_CUDA_NO_VMM)
$(RAM_PROFILE_TARGETS): ENABLE_CUDA_GRAPHS := $(WHISPER_RAM_ENABLE_CUDA_GRAPHS)
$(RAM_PROFILE_TARGETS): ENABLE_CUDA_NCCL := $(WHISPER_RAM_ENABLE_CUDA_NCCL)
$(RAM_PROFILE_TARGETS): CUDA_COMPRESSION_MODE := $(WHISPER_RAM_CUDA_COMPRESSION_MODE)
$(RAM_PROFILE_TARGETS): ENABLE_CUDA_GLIBC_COMPAT := $(WHISPER_RAM_ENABLE_CUDA_GLIBC_COMPAT)
$(RAM_PROFILE_TARGETS): CUDA_GLIBC_HEADER := $(WHISPER_RAM_CUDA_GLIBC_HEADER)
$(RAM_PROFILE_TARGETS): CUDA_GLIBC_COMPAT_DIR := $(WHISPER_RAM_CUDA_GLIBC_COMPAT_DIR)
$(RAM_PROFILE_TARGETS): ENABLE_HIP := $(WHISPER_RAM_ENABLE_HIP)
$(RAM_PROFILE_TARGETS): AMDGPU_TARGETS := $(WHISPER_RAM_AMDGPU_TARGETS)
$(RAM_PROFILE_TARGETS): ENABLE_VULKAN := $(WHISPER_RAM_ENABLE_VULKAN)
$(RAM_PROFILE_TARGETS): ENABLE_SYCL := $(WHISPER_RAM_ENABLE_SYCL)
$(RAM_PROFILE_TARGETS): ENABLE_SYCL_F16 := $(WHISPER_RAM_ENABLE_SYCL_F16)
$(RAM_PROFILE_TARGETS): SYCL_TARGET := $(WHISPER_RAM_SYCL_TARGET)
$(RAM_PROFILE_TARGETS): SYCL_DEVICE_ARCH := $(WHISPER_RAM_SYCL_DEVICE_ARCH)
$(RAM_PROFILE_TARGETS): ENABLE_OPENVINO := $(WHISPER_RAM_ENABLE_OPENVINO)
$(RAM_PROFILE_TARGETS): ENABLE_FFMPEG := $(WHISPER_RAM_ENABLE_FFMPEG)
$(RAM_PROFILE_TARGETS): STRIP_BINARY := $(WHISPER_RAM_STRIP_BINARY)
$(RAM_PROFILE_TARGETS): EXTRA_CMAKE_ARGS := $(WHISPER_RAM_EXTRA_CMAKE_ARGS)
$(RAM_PROFILE_TARGETS): EXTRA_C_FLAGS := $(WHISPER_RAM_EXTRA_C_FLAGS)
$(RAM_PROFILE_TARGETS): EXTRA_CXX_FLAGS := $(WHISPER_RAM_EXTRA_CXX_FLAGS)
$(RAM_PROFILE_TARGETS): EXTRA_CUDA_FLAGS := $(WHISPER_RAM_EXTRA_CUDA_FLAGS)

$(CUDA_PROFILE_TARGETS): BUILD_PROFILE := cuda
$(CUDA_PROFILE_TARGETS): SOURCE_DIR := $(WHISPER_CUDA_SOURCE_DIR)
$(CUDA_PROFILE_TARGETS): BUILD_DIR := $(WHISPER_CUDA_BUILD_DIR)
$(CUDA_PROFILE_TARGETS): OUTPUT_DIR := $(WHISPER_CUDA_OUTPUT_DIR)
$(CUDA_PROFILE_TARGETS): MODEL_DIR := $(WHISPER_CUDA_MODEL_DIR)
$(CUDA_PROFILE_TARGETS): ARCHIVE_PATH := $(WHISPER_CUDA_ARCHIVE_PATH)
$(CUDA_PROFILE_TARGETS): SCCACHE_DIR := $(WHISPER_CUDA_SCCACHE_DIR)
$(CUDA_PROFILE_TARGETS): SCCACHE_SERVER_UDS := $(WHISPER_CUDA_SCCACHE_SERVER_UDS)
$(CUDA_PROFILE_TARGETS): CMAKE_GENERATOR := $(WHISPER_CUDA_CMAKE_GENERATOR)
$(CUDA_PROFILE_TARGETS): BUILD_JOBS := $(WHISPER_CUDA_BUILD_JOBS)
$(CUDA_PROFILE_TARGETS): CMAKE_C_COMPILER := $(WHISPER_CUDA_CMAKE_C_COMPILER)
$(CUDA_PROFILE_TARGETS): CMAKE_CXX_COMPILER := $(WHISPER_CUDA_CMAKE_CXX_COMPILER)
$(CUDA_PROFILE_TARGETS): CMAKE_CUDA_COMPILER := $(WHISPER_CUDA_CMAKE_CUDA_COMPILER)
$(CUDA_PROFILE_TARGETS): CMAKE_CUDA_HOST_COMPILER := $(WHISPER_CUDA_CMAKE_CUDA_HOST_COMPILER)
$(CUDA_PROFILE_TARGETS): CMAKE_C_COMPILER_LAUNCHER := $(WHISPER_CUDA_CMAKE_C_COMPILER_LAUNCHER)
$(CUDA_PROFILE_TARGETS): CMAKE_CXX_COMPILER_LAUNCHER := $(WHISPER_CUDA_CMAKE_CXX_COMPILER_LAUNCHER)
$(CUDA_PROFILE_TARGETS): CMAKE_CUDA_COMPILER_LAUNCHER := $(WHISPER_CUDA_CMAKE_CUDA_COMPILER_LAUNCHER)
$(CUDA_PROFILE_TARGETS): CMAKE_C_FLAGS := $(WHISPER_CUDA_CMAKE_C_FLAGS)
$(CUDA_PROFILE_TARGETS): CMAKE_CXX_FLAGS := $(WHISPER_CUDA_CMAKE_CXX_FLAGS)
$(CUDA_PROFILE_TARGETS): CMAKE_CUDA_FLAGS := $(WHISPER_CUDA_CMAKE_CUDA_FLAGS)
$(CUDA_PROFILE_TARGETS): BUILD_CLI := $(WHISPER_CUDA_BUILD_CLI)
$(CUDA_PROFILE_TARGETS): BUILD_SERVER := $(WHISPER_CUDA_BUILD_SERVER)
$(CUDA_PROFILE_TARGETS): GGML_NATIVE := $(WHISPER_CUDA_GGML_NATIVE)
$(CUDA_PROFILE_TARGETS): ENABLE_LTO := $(WHISPER_CUDA_ENABLE_LTO)
$(CUDA_PROFILE_TARGETS): ENABLE_CCACHE := $(WHISPER_CUDA_ENABLE_CCACHE)
$(CUDA_PROFILE_TARGETS): ENABLE_OPENMP := $(WHISPER_CUDA_ENABLE_OPENMP)
$(CUDA_PROFILE_TARGETS): ENABLE_CPU_REPACK := $(WHISPER_CUDA_ENABLE_CPU_REPACK)
$(CUDA_PROFILE_TARGETS): ENABLE_FAST_MATH := $(WHISPER_CUDA_ENABLE_FAST_MATH)
$(CUDA_PROFILE_TARGETS): ENABLE_BLAS := $(WHISPER_CUDA_ENABLE_BLAS)
$(CUDA_PROFILE_TARGETS): BLAS_VENDOR := $(WHISPER_CUDA_BLAS_VENDOR)
$(CUDA_PROFILE_TARGETS): ENABLE_CUDA := $(WHISPER_CUDA_ENABLE_CUDA)
$(CUDA_PROFILE_TARGETS): CUDA_ARCHS := $(WHISPER_CUDA_CUDA_ARCHS)
$(CUDA_PROFILE_TARGETS): ENABLE_CUDA_FA := $(WHISPER_CUDA_ENABLE_CUDA_FA)
$(CUDA_PROFILE_TARGETS): ENABLE_CUDA_FA_ALL_QUANTS := $(WHISPER_CUDA_ENABLE_CUDA_FA_ALL_QUANTS)
$(CUDA_PROFILE_TARGETS): CUDA_FORCE_MMQ := $(WHISPER_CUDA_CUDA_FORCE_MMQ)
$(CUDA_PROFILE_TARGETS): CUDA_FORCE_CUBLAS := $(WHISPER_CUDA_CUDA_FORCE_CUBLAS)
$(CUDA_PROFILE_TARGETS): CUDA_NO_PEER_COPY := $(WHISPER_CUDA_CUDA_NO_PEER_COPY)
$(CUDA_PROFILE_TARGETS): CUDA_NO_VMM := $(WHISPER_CUDA_CUDA_NO_VMM)
$(CUDA_PROFILE_TARGETS): ENABLE_CUDA_GRAPHS := $(WHISPER_CUDA_ENABLE_CUDA_GRAPHS)
$(CUDA_PROFILE_TARGETS): ENABLE_CUDA_NCCL := $(WHISPER_CUDA_ENABLE_CUDA_NCCL)
$(CUDA_PROFILE_TARGETS): CUDA_COMPRESSION_MODE := $(WHISPER_CUDA_CUDA_COMPRESSION_MODE)
$(CUDA_PROFILE_TARGETS): ENABLE_CUDA_GLIBC_COMPAT := $(WHISPER_CUDA_ENABLE_CUDA_GLIBC_COMPAT)
$(CUDA_PROFILE_TARGETS): CUDA_GLIBC_HEADER := $(WHISPER_CUDA_CUDA_GLIBC_HEADER)
$(CUDA_PROFILE_TARGETS): CUDA_GLIBC_COMPAT_DIR := $(WHISPER_CUDA_CUDA_GLIBC_COMPAT_DIR)
$(CUDA_PROFILE_TARGETS): ENABLE_HIP := $(WHISPER_CUDA_ENABLE_HIP)
$(CUDA_PROFILE_TARGETS): AMDGPU_TARGETS := $(WHISPER_CUDA_AMDGPU_TARGETS)
$(CUDA_PROFILE_TARGETS): ENABLE_VULKAN := $(WHISPER_CUDA_ENABLE_VULKAN)
$(CUDA_PROFILE_TARGETS): ENABLE_SYCL := $(WHISPER_CUDA_ENABLE_SYCL)
$(CUDA_PROFILE_TARGETS): ENABLE_SYCL_F16 := $(WHISPER_CUDA_ENABLE_SYCL_F16)
$(CUDA_PROFILE_TARGETS): SYCL_TARGET := $(WHISPER_CUDA_SYCL_TARGET)
$(CUDA_PROFILE_TARGETS): SYCL_DEVICE_ARCH := $(WHISPER_CUDA_SYCL_DEVICE_ARCH)
$(CUDA_PROFILE_TARGETS): ENABLE_OPENVINO := $(WHISPER_CUDA_ENABLE_OPENVINO)
$(CUDA_PROFILE_TARGETS): ENABLE_FFMPEG := $(WHISPER_CUDA_ENABLE_FFMPEG)
$(CUDA_PROFILE_TARGETS): STRIP_BINARY := $(WHISPER_CUDA_STRIP_BINARY)
$(CUDA_PROFILE_TARGETS): EXTRA_CMAKE_ARGS := $(WHISPER_CUDA_EXTRA_CMAKE_ARGS)
$(CUDA_PROFILE_TARGETS): EXTRA_C_FLAGS := $(WHISPER_CUDA_EXTRA_C_FLAGS)
$(CUDA_PROFILE_TARGETS): EXTRA_CXX_FLAGS := $(WHISPER_CUDA_EXTRA_CXX_FLAGS)
$(CUDA_PROFILE_TARGETS): EXTRA_CUDA_FLAGS := $(WHISPER_CUDA_EXTRA_CUDA_FLAGS)

MODEL ?=
AUDIO ?=
ARGS ?=
CONFIRM ?=

export ROOT_DIR WHISPER_CPP_REPO WHISPER_CPP_REF SOURCE_DIR BUILD_DIR OUTPUT_DIR MODEL_DIR BUILD_PROFILE ARCHIVE_PATH
export CMAKE_GENERATOR BUILD_JOBS CMAKE_C_COMPILER CMAKE_CXX_COMPILER CMAKE_CUDA_COMPILER CMAKE_CUDA_HOST_COMPILER
export CMAKE_C_COMPILER_LAUNCHER CMAKE_CXX_COMPILER_LAUNCHER CMAKE_CUDA_COMPILER_LAUNCHER
export CMAKE_C_FLAGS CMAKE_CXX_FLAGS CMAKE_CUDA_FLAGS SCCACHE_DIR SCCACHE_SERVER_UDS
export BUILD_CLI BUILD_SERVER GGML_NATIVE
export ENABLE_LTO ENABLE_CCACHE ENABLE_OPENMP ENABLE_CPU_REPACK ENABLE_FAST_MATH
export ENABLE_BLAS BLAS_VENDOR ENABLE_CUDA CUDA_ARCHS ENABLE_CUDA_FA ENABLE_CUDA_FA_ALL_QUANTS
export CUDA_FORCE_MMQ CUDA_FORCE_CUBLAS CUDA_NO_PEER_COPY CUDA_NO_VMM ENABLE_CUDA_GRAPHS ENABLE_CUDA_NCCL
export CUDA_COMPRESSION_MODE ENABLE_CUDA_GLIBC_COMPAT CUDA_GLIBC_HEADER CUDA_GLIBC_COMPAT_DIR
export ENABLE_HIP AMDGPU_TARGETS ENABLE_VULKAN ENABLE_SYCL ENABLE_SYCL_F16 SYCL_TARGET SYCL_DEVICE_ARCH
export ENABLE_OPENVINO ENABLE_FFMPEG STRIP_BINARY OFFLINE SOURCE_UPDATE FORCE_SOURCE_RESET
export STRICT_RESOURCES FORCE_DOWNLOAD ALLOW_EXTERNAL_DIRS RUNTIME_THREADS
export EXTRA_CMAKE_ARGS EXTRA_C_FLAGS EXTRA_CXX_FLAGS EXTRA_CUDA_FLAGS

.PHONY: help doctor source update-source configure build rebuild verify info print-config
.PHONY: models download run test clean distclean purge
.PHONY: build-ram build-cuda doctor-ram doctor-cuda info-ram info-cuda
.PHONY: verify-ram verify-cuda clean-ram clean-cuda

help: ## Show available targets
	@awk 'BEGIN {FS = ":.*## "; printf "whisper.cpp native builder\n\nUsage:\n  make <target> [VARIABLE=value ...]\n\nTargets:\n"} /^[a-zA-Z0-9_.-]+:.*## / {printf "  %-16s %s\n", $$1, $$2}' $(MAKEFILE_LIST)
	@printf '\nExamples:\n  make build-ram\n  make build-cuda\n  make info-cuda\n  make download MODEL=base.en\n  make run MODEL=base.en AUDIO=/path/to/audio.wav ARGS="--output-txt"\n'

doctor: ## Check compilers, CMake, and enabled accelerator dependencies
	@CONFIG_FROM_MAKE=1 "$(ROOT_DIR)/scripts/doctor.sh"

source: ## Fetch the configured whisper.cpp source ref without installing it
	@CONFIG_FROM_MAKE=1 "$(ROOT_DIR)/scripts/source.sh"

update-source: ## Force-refresh the configured source ref
	@CONFIG_FROM_MAKE=1 SOURCE_UPDATE=1 "$(ROOT_DIR)/scripts/source.sh"

configure: ## Run checks, fetch source, and generate the native Release build
	@CONFIG_FROM_MAKE=1 "$(ROOT_DIR)/scripts/doctor.sh"
	@CONFIG_FROM_MAKE=1 "$(ROOT_DIR)/scripts/source.sh"
	@CONFIG_FROM_MAKE=1 "$(ROOT_DIR)/scripts/configure.sh"

build: ## Compile whisper-cli and whisper-server with the generic profile
	@CONFIG_FROM_MAKE=1 "$(ROOT_DIR)/scripts/doctor.sh"
	@CONFIG_FROM_MAKE=1 "$(ROOT_DIR)/scripts/source.sh"
	@CONFIG_FROM_MAKE=1 "$(ROOT_DIR)/scripts/configure.sh"
	@CONFIG_FROM_MAKE=1 "$(ROOT_DIR)/scripts/build.sh"
	@CONFIG_FROM_MAKE=1 "$(ROOT_DIR)/scripts/verify.sh"

build-ram: ## Build CPU/RAM binaries and create whisper-ram.tar.gz
	@CONFIG_FROM_MAKE=1 "$(ROOT_DIR)/scripts/doctor.sh"
	@CONFIG_FROM_MAKE=1 "$(ROOT_DIR)/scripts/source.sh"
	@CONFIG_FROM_MAKE=1 "$(ROOT_DIR)/scripts/configure.sh"
	@CONFIG_FROM_MAKE=1 "$(ROOT_DIR)/scripts/build.sh"
	@CONFIG_FROM_MAKE=1 "$(ROOT_DIR)/scripts/verify.sh"
	@CONFIG_FROM_MAKE=1 "$(ROOT_DIR)/scripts/package.sh"

build-cuda: ## Build Quadro P520 sm_61 CUDA binaries and create whisper-cuda.tar.gz
	@CONFIG_FROM_MAKE=1 "$(ROOT_DIR)/scripts/doctor.sh"
	@CONFIG_FROM_MAKE=1 "$(ROOT_DIR)/scripts/source.sh"
	@CONFIG_FROM_MAKE=1 "$(ROOT_DIR)/scripts/configure.sh"
	@CONFIG_FROM_MAKE=1 "$(ROOT_DIR)/scripts/build.sh"
	@CONFIG_FROM_MAKE=1 "$(ROOT_DIR)/scripts/verify.sh"
	@CONFIG_FROM_MAKE=1 "$(ROOT_DIR)/scripts/package.sh"

doctor-ram: ## Check the CPU/RAM profile toolchain
	@CONFIG_FROM_MAKE=1 "$(ROOT_DIR)/scripts/doctor.sh"

doctor-cuda: ## Check the CUDA sm_61 profile toolchain and nvcc support
	@CONFIG_FROM_MAKE=1 "$(ROOT_DIR)/scripts/doctor.sh"

rebuild: ## Remove build products, then rebuild from scratch
	@$(MAKE) --no-print-directory clean
	@$(MAKE) --no-print-directory build

verify: ## Verify staged whisper-cli/whisper-server and dynamic dependencies
	@CONFIG_FROM_MAKE=1 "$(ROOT_DIR)/scripts/verify.sh"

verify-ram: ## Verify staged CPU/RAM binaries
	@CONFIG_FROM_MAKE=1 "$(ROOT_DIR)/scripts/verify.sh"

verify-cuda: ## Verify staged CUDA binaries
	@CONFIG_FROM_MAKE=1 "$(ROOT_DIR)/scripts/verify.sh"

info: ## Print the effective build configuration
	@CONFIG_FROM_MAKE=1 "$(ROOT_DIR)/scripts/print-config.sh"

info-ram: ## Print the resolved CPU/RAM profile
	@CONFIG_FROM_MAKE=1 "$(ROOT_DIR)/scripts/print-config.sh"

info-cuda: ## Print the resolved Quadro P520 CUDA profile
	@CONFIG_FROM_MAKE=1 "$(ROOT_DIR)/scripts/print-config.sh"

print-config: info ## Alias for make info

models: ## Print the complete curated GGML model table
	@CONFIG_FROM_MAKE=1 "$(ROOT_DIR)/scripts/download-model.sh" --list

download: ## Interactively select a model, or use MODEL=<name>
	@CONFIG_FROM_MAKE=1 MODEL="$(MODEL)" HF_TOKEN="$(HF_TOKEN)" "$(ROOT_DIR)/scripts/download-model.sh"

run: ## Run staged whisper-cli; requires AUDIO=..., MODEL defaults to base.en
	@CONFIG_FROM_MAKE=1 MODEL="$(MODEL)" AUDIO="$(AUDIO)" RUN_ARGS="$(ARGS)" "$(ROOT_DIR)/scripts/run.sh"

test: ## Run syntax, manifest, and end-to-end wrapper tests
	@"$(ROOT_DIR)/tests/run.sh"

clean: ## Remove the generic build and staged binaries; preserve models/source
	@CONFIG_FROM_MAKE=1 "$(ROOT_DIR)/scripts/clean.sh" build

clean-ram: ## Remove RAM build/staged binaries; preserve source/models/archive
	@CONFIG_FROM_MAKE=1 "$(ROOT_DIR)/scripts/clean.sh" build

clean-cuda: ## Remove CUDA build/staged binaries; preserve source/models/archive
	@CONFIG_FROM_MAKE=1 "$(ROOT_DIR)/scripts/clean.sh" build

distclean: ## Also remove the managed whisper.cpp source; preserve models
	@CONFIG_FROM_MAKE=1 "$(ROOT_DIR)/scripts/clean.sh" distclean

purge: ## Remove build, source, binary, and downloaded models; requires CONFIRM=YES
	@CONFIG_FROM_MAKE=1 CONFIRM="$(CONFIRM)" "$(ROOT_DIR)/scripts/clean.sh" purge
